TAP5-2582: Service creation for Hibernate Session results in
ClassFormatError: Duplicate method name&signature
# Conflicts:
#	plastic/src/main/java/org/apache/tapestry5/internal/plastic/PlasticClassImpl.java